import React, { useState } from 'react';
import logo from './logo.svg';
// import './App.css';

import styles from './Home.module.css'

async function getWords(operators: WordOperation[]): Promise<WordPrediction[]> {
  const res = await fetch('/operations', {
    method: 'POST',
    headers: {
      'Content-type': 'application/json',
    },
    body: JSON.stringify(operators),
  })
  
  if(!res.ok){
    throw new Error(`Response failed with code ${res.status} - ${res.statusText}`);
  }
  
  const parsedResp = await res.json() as unknown as WordOperation[];
  console.log("Response: ", parsedResp)
  if(parsedResp.length >= 1) {
    console.log("Response results:", parsedResp[parsedResp.length - 1].results)
   
    // Return the results directly or an empty array 
    return parsedResp[parsedResp.length - 1].results || [] as WordPrediction[];
  }

  return [];
}

type WordAction = "start" | "more_like" | "less_like"

interface WordPrediction { word: string; dist: number };

type WordOperation = {
  id?: string,
  function: WordAction,
  description: string,
  results?: WordPrediction[],
  selected_words?: string[]
}

const initialAppState = {
  ops: [{ description: '', function: 'start' }] as WordOperation[],
  predictions: []
}
function App() {
  const [operators, setOperators] = useState<WordOperation[]>(initialAppState.ops);
  const [predictions, setPredictions] = useState<WordPrediction[]>(initialAppState.predictions);

  const handleAddOperator = () => {
    setOperators([...operators, { description: '', function: 'more_like' }]);
  };

  const handleOperatorChange = (index: number, field: keyof WordOperation, value: any) => {
    const updatedOperators = [...operators];
    updatedOperators[index][field] = value;
    setOperators(updatedOperators);
    // calculateWords(updatedOperators);
  };

  const handleRemoveOperator = (index: number) => {
    const updatedOperators = [...operators];
    updatedOperators.splice(index, 1);
    setOperators(updatedOperators);
    // calculateWords(updatedOperators);
  };
//
  const calculateWords = (operators: WordOperation[]) => {
    operators = operators.filter(operator => operator.description !== "" && operator.description !== null);
    getWords(operators).then((latest_results: WordPrediction[]) => {
      console.log("Got results: ", latest_results);
      setPredictions(latest_results);
    }).catch(e => console.log)
  };

  console.log("Predictions: ", predictions);
  console.log("Operators: ", operators);

  function resetApp(): void {
    setOperators(initialAppState.ops);
    setPredictions(initialAppState.predictions);
  }

  return (
    <div className={styles.container}>
      <div>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Tip of My Tongue
        </h1>

        <p className={styles.description}>
          It's 2023... why are we still using a thesaurus?
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>I'm thinking of a word...</h2>

            {operators.map((operator, index) => (
              <div key={index} style={{ display: 'flex', alignItems: 'center', marginBottom: '10px' }}>
                <input
                  type="text"
                  value={operator.description}
                  onChange={(e) => handleOperatorChange(index, 'description', e.target.value)}
                  style={{ marginRight: '10px' }}
                />
                
                {/* Word Function Operator Dropdown */}
                {index > 0 && (
                <select
                  value={operator.function}
                  onChange={(e) => handleOperatorChange(index, 'function', e.target.value as 'more' | 'less')}
                  style={{ marginRight: '10px' }}
                >
                  <option value="more_like">Like this</option>
                  <option value="less_like">Not like this</option>
                </select>
                )}

                {/* Remove Operator Button */}
                {index > 0 && (
                  <button onClick={() => handleRemoveOperator(index)} style={{ marginRight: '10px' }}>X</button>
                )}
              </div>
            ))}
            <button onClick={handleAddOperator}>Add Operator</button>
            <button onClick={() => calculateWords(operators)}>Get Words</button>
            <button onClick={() => resetApp()}>Start Over</button>
          </div>
        </div>

        <div>
          {predictions.map((prediction, index) => (
            <div key={index}>
              <span>{prediction.word}</span>
              <span>{prediction.dist}</span>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built on
          <span className={styles.logo}>
            <img src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
          Replit
        </a>
      </footer>
    </div>
  )
}

export default App;
