version: '3.8'

services:
  app:
    build:
      context: ./api
    environment:
        OPENAI_API_KEY: ""
    volumes:
      - "./api/res:/src/res:ro"
    depends_on:
      - triton-server

  ui_server:
    build:
      context: ./webapp
    environment:
      API_SERVER: "app:8000" # Frontend Nginx router proxies to the "app" container
    ports:
      - "8080:80"
    depends_on:
      - app

  triton-server:
    build:
      context: ./triton
    volumes:
      - "./triton:/models:rw"
    ports:
      - "8100:8100"