version: '3.8'

services:
  app:
    build: 
      context: ./api
    environment:
        OPENAI_API_KEY: ""
    volumes:
      - ./api/res:/src/res:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ui_server: 
    build:
      context: ./webapp
    environment:
      API_SERVER: "app:8000" # Frontend Nginx router proxies to the "app" container
    ports:
      - 8080:80