name: "postprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [ -1, -1, 1024 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ -1, -1, 1024 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]

model_warmup [
{
    name : "postprocess"
    batch_size: 1
    count: 1
    inputs {
      key: "last_hidden_state"
      value: {
        data_type: TYPE_FP32
        dims: 1
        dims: 3
        dims: 1024
        input_data_file: "last_hidden_state"
      }
    }
    inputs {
      key: "attention_mask"
      value: {
        data_type: TYPE_INT64
        dims: 1
        dims: 3
        input_data_file: "attention_mask"
      }
    }
}]

version_policy: { 
  latest: { num_versions: 1 }
}

response_cache { 
  enable: True 
}